commerce_payment.commerce_payment_gateway.plugin.usaepay:
  type: commerce_payment_gateway_configuration
  mapping:
    wsdl_key:
      type: string
      label: 'WSDL Key'
    source_key:
      type: string
      label: 'Source Key'
    pin:
      type: string
      label: 'PIN'
